spring.application.name=koreatourism
#8080\uD3EC\uD2B8 \uC0AC\uC6A9\uC911\uC774\uB77C \uB2E4\uB978 \uD3EC\uD2B8\uB85C \uB300\uCCB4
server.port=8443

#DB \uB4DC\uB77C\uC774\uBC84 \uC124\uC815
spring.datasource.url=jdbc:h2:mem:testdb;MODE=MySQL
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
#spring.datasource.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

#MyBatis
mybatis.type-aliases-package=com.kotu.koreatourism.domain
logging.level.com.kotu.koreatourism.mapper=debug
logging.level.org.mybatis=debug
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath:mapper/**/*.xml
#\uB85C\uADF8\uC5D0 sql\uCD9C\uB825
#mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

#HTTP \uC694\uCCAD \uBA54\uC2DC\uC9C0 \uB85C\uAE45
logging.level.org.apache.coyote.http11=debug
#\uC2A4\uD504\uB9C1 \uC2DC\uD050\uB9AC\uD2F0 \uB85C\uAE45
logging.level.org.springframework.security=DEBUG

#\uACF5\uACF5\uB370\uC774\uD130 \uC778\uC99D\uD0A4 incoding
openapi.servicekeye=W2%2FNzPGs6c1IxnHCzSpB7LZJ5rqfNC4yQpItleRwMyTJ16VOM1xOu7jdOIcyJYBWooCe2HXdXaW76tT%2BbGM8MQ%3D%3D
#\uACF5\uACF5\uB370\uC774\uD130 \uC778\uC99D\uD0A4 decoding
openapi.servicekeyd=W2/NzPGs6c1IxnHCzSpB7LZJ5rqfNC4yQpItleRwMyTJ16VOM1xOu7jdOIcyJYBWooCe2HXdXaW76tT+bGM8MQ==
openapi.callbackurl.kor=http://apis.data.go.kr/B551011/KorService1
openapi.callbackurl.eng=http://apis.data.go.kr/B551011/EngService1
openapi.datatype=json

# \uAD6C\uAE00 \uB9F5\uC2A4 api key
googlemapapi=

#Oauth2 \uC778\uC99D
#Google
spring.security.oauth2.client.registration.google.client-id=1058341118420-tkfmthji9iumecue8sud2h8c63ort85v.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.redirect-uri=https://localhost:8443/login/oauth2/code/google
spring.security.oauth2.client.registration.google.authorization-method=authorization_code
spring.security.oauth2.client.registration.google.client-authentication-method=client_secret_post
spring.security.oauth2.client.registration.google.client-name=Google
spring.security.oauth2.client.registration.google.scope=profile,email

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v2/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=id

#Kakao
spring.security.oauth2.client.registration.kakao.client_id=6492ae243fad28329b2428bf1c3cb018
spring.security.oauth2.client.registration.kakao.client-secret=1xhCnCmquzi1BSejRlz1Arvu21B33HFh
spring.security.oauth2.client.registration.kakao.redirect-uri=https://localhost:8443/login/oauth2/code/kakao
spring.security.oauth2.client.registration.kakao.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.kakao.client-authentication-method=client_secret_post
spring.security.oauth2.client.registration.kakao.client-name=Kakao
spring.security.oauth2.client.registration.kakao.scope=profile_nickname,profile_image,account_email

spring.security.oauth2.client.provider.kakao.authorization-uri=https://kauth.kakao.com/oauth/authorize
spring.security.oauth2.client.provider.kakao.token-uri=https://kauth.kakao.com/oauth/token
spring.security.oauth2.client.provider.kakao.user-info-uri=https://kapi.kakao.com/v2/user/me
spring.security.oauth2.client.provider.kakao.user-name-attribute=id


spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML

#Local ssl \uD658\uACBD\uC124\uC815
server.ssl.enabled=true
server.ssl.key-store-type=PKCS12
server.ssl.key-store=keystore.p12
server.ssl.key-store-password=xlfksh5791!
server.ssl.key-alias=kotu-ssl
